//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekDunyası
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADMİN
    {
        public int AdminID { get; set; }
        public string AdminAD { get; set; }
        public string AdminSifre { get; set; }
    }
}
