//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekDunyası.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SIPARIS
    {
        public int SiparisID { get; set; }
        public Nullable<int> SiparisRestoranID { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<decimal> SiparisTutar { get; set; }
        public Nullable<int> SiparisUrunID { get; set; }
        public int SiparisKullaniciID { get; set; }
        public Nullable<bool> SiparisDurum { get; set; }
        public string SiparisBilgi { get; set; }
        public Nullable<int> SiparisAdet { get; set; }
    
        public virtual TBL_MUSTERI TBL_MUSTERI { get; set; }
        public virtual TBL_MUSTERI TBL_MUSTERI1 { get; set; }
        public virtual TBL_RESTORAN TBL_RESTORAN { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
