//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekDunyası.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RESTORAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_RESTORAN()
        {
            this.TBL_SIPARIS = new HashSet<TBL_SIPARIS>();
        }
    
        public int RestoranID { get; set; }
        public string RestoranAD { get; set; }
        public Nullable<decimal> RestoranPUAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SIPARIS> TBL_SIPARIS { get; set; }
    }
}
