//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekDunyası.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SEPET
    {
        public int SepetID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> UrunEklenen { get; set; }
        public Nullable<int> KullanıcıID { get; set; }
    
        public virtual TBL_MUSTERI TBL_MUSTERI { get; set; }
    }
}
